#############################################################################
# Makefile for building: JsonEditor
# Generated by qmake (3.1) (Qt 5.15.10)
# Project:  JsonEditor.pro
# Template: app
# Command: /opt/qt5/bin/qmake -o Makefile JsonEditor.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/qt-5.15.10/include -I/opt/qt-5.15.10/include/QtWidgets -I/opt/qt-5.15.10/include/QtGui -I/opt/qt-5.15.10/include/QtNetwork -I/opt/qt-5.15.10/include/QtCore -I. -I/usr/include/libdrm -I/opt/qt-5.15.10/mkspecs/linux-g++
QMAKE         = /opt/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = JsonEditor1.0.0
DISTDIR = /home/tigran/ProjectWithAi/JsonEditor/.tmp/JsonEditor1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /opt/qt-5.15.10/lib/libQt5Widgets.so /opt/qt-5.15.10/lib/libQt5Gui.so /opt/qt-5.15.10/lib/libQt5Network.so /opt/qt-5.15.10/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		JsonEditorDialog.cpp moc_JsonEditorDialog.cpp
OBJECTS       = main.o \
		JsonEditorDialog.o \
		moc_JsonEditorDialog.o
DIST          = /opt/qt-5.15.10/mkspecs/features/spec_pre.prf \
		/opt/qt-5.15.10/mkspecs/common/unix.conf \
		/opt/qt-5.15.10/mkspecs/common/linux.conf \
		/opt/qt-5.15.10/mkspecs/common/sanitize.conf \
		/opt/qt-5.15.10/mkspecs/common/gcc-base.conf \
		/opt/qt-5.15.10/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-5.15.10/mkspecs/common/g++-base.conf \
		/opt/qt-5.15.10/mkspecs/common/g++-unix.conf \
		/opt/qt-5.15.10/mkspecs/qconfig.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_core.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_help.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_location.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_network.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_script.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt-5.15.10/mkspecs/features/qt_functions.prf \
		/opt/qt-5.15.10/mkspecs/features/qt_config.prf \
		/opt/qt-5.15.10/mkspecs/linux-g++/qmake.conf \
		/opt/qt-5.15.10/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt-5.15.10/mkspecs/features/exclusive_builds.prf \
		/opt/qt-5.15.10/mkspecs/features/toolchain.prf \
		/opt/qt-5.15.10/mkspecs/features/default_pre.prf \
		/opt/qt-5.15.10/mkspecs/features/resolve_config.prf \
		/opt/qt-5.15.10/mkspecs/features/default_post.prf \
		/opt/qt-5.15.10/mkspecs/features/warn_on.prf \
		/opt/qt-5.15.10/mkspecs/features/qt.prf \
		/opt/qt-5.15.10/mkspecs/features/resources_functions.prf \
		/opt/qt-5.15.10/mkspecs/features/resources.prf \
		/opt/qt-5.15.10/mkspecs/features/moc.prf \
		/opt/qt-5.15.10/mkspecs/features/unix/opengl.prf \
		/opt/qt-5.15.10/mkspecs/features/uic.prf \
		/opt/qt-5.15.10/mkspecs/features/unix/thread.prf \
		/opt/qt-5.15.10/mkspecs/features/qmake_use.prf \
		/opt/qt-5.15.10/mkspecs/features/file_copies.prf \
		/opt/qt-5.15.10/mkspecs/features/testcase_targets.prf \
		/opt/qt-5.15.10/mkspecs/features/exceptions.prf \
		/opt/qt-5.15.10/mkspecs/features/yacc.prf \
		/opt/qt-5.15.10/mkspecs/features/lex.prf \
		JsonEditor.pro JsonEditorDialog.h main.cpp \
		JsonEditorDialog.cpp
QMAKE_TARGET  = JsonEditor
DESTDIR       = 
TARGET        = JsonEditor


first: all
####### Build rules

JsonEditor:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: JsonEditor.pro /opt/qt-5.15.10/mkspecs/linux-g++/qmake.conf /opt/qt-5.15.10/mkspecs/features/spec_pre.prf \
		/opt/qt-5.15.10/mkspecs/common/unix.conf \
		/opt/qt-5.15.10/mkspecs/common/linux.conf \
		/opt/qt-5.15.10/mkspecs/common/sanitize.conf \
		/opt/qt-5.15.10/mkspecs/common/gcc-base.conf \
		/opt/qt-5.15.10/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-5.15.10/mkspecs/common/g++-base.conf \
		/opt/qt-5.15.10/mkspecs/common/g++-unix.conf \
		/opt/qt-5.15.10/mkspecs/qconfig.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_core.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_help.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_location.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_network.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_script.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt-5.15.10/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt-5.15.10/mkspecs/features/qt_functions.prf \
		/opt/qt-5.15.10/mkspecs/features/qt_config.prf \
		/opt/qt-5.15.10/mkspecs/linux-g++/qmake.conf \
		/opt/qt-5.15.10/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt-5.15.10/mkspecs/features/exclusive_builds.prf \
		/opt/qt-5.15.10/mkspecs/features/toolchain.prf \
		/opt/qt-5.15.10/mkspecs/features/default_pre.prf \
		/opt/qt-5.15.10/mkspecs/features/resolve_config.prf \
		/opt/qt-5.15.10/mkspecs/features/default_post.prf \
		/opt/qt-5.15.10/mkspecs/features/warn_on.prf \
		/opt/qt-5.15.10/mkspecs/features/qt.prf \
		/opt/qt-5.15.10/mkspecs/features/resources_functions.prf \
		/opt/qt-5.15.10/mkspecs/features/resources.prf \
		/opt/qt-5.15.10/mkspecs/features/moc.prf \
		/opt/qt-5.15.10/mkspecs/features/unix/opengl.prf \
		/opt/qt-5.15.10/mkspecs/features/uic.prf \
		/opt/qt-5.15.10/mkspecs/features/unix/thread.prf \
		/opt/qt-5.15.10/mkspecs/features/qmake_use.prf \
		/opt/qt-5.15.10/mkspecs/features/file_copies.prf \
		/opt/qt-5.15.10/mkspecs/features/testcase_targets.prf \
		/opt/qt-5.15.10/mkspecs/features/exceptions.prf \
		/opt/qt-5.15.10/mkspecs/features/yacc.prf \
		/opt/qt-5.15.10/mkspecs/features/lex.prf \
		JsonEditor.pro
	$(QMAKE) -o Makefile JsonEditor.pro
/opt/qt-5.15.10/mkspecs/features/spec_pre.prf:
/opt/qt-5.15.10/mkspecs/common/unix.conf:
/opt/qt-5.15.10/mkspecs/common/linux.conf:
/opt/qt-5.15.10/mkspecs/common/sanitize.conf:
/opt/qt-5.15.10/mkspecs/common/gcc-base.conf:
/opt/qt-5.15.10/mkspecs/common/gcc-base-unix.conf:
/opt/qt-5.15.10/mkspecs/common/g++-base.conf:
/opt/qt-5.15.10/mkspecs/common/g++-unix.conf:
/opt/qt-5.15.10/mkspecs/qconfig.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3danimation.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dextras.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3drender.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_charts.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_charts_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_core.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_designer.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_gamepad.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_glx_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_gui.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_help.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_location.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_network.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_networkauth.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_purchasing.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_qml.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3d.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3drender.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3drender_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_repparser.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_script.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_scxml.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_serialbus.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_sql.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_svg.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_waylandclient.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_waylandclient_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_waylandcompositor.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_webview.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_webview_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_xml.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt-5.15.10/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt-5.15.10/mkspecs/features/qt_functions.prf:
/opt/qt-5.15.10/mkspecs/features/qt_config.prf:
/opt/qt-5.15.10/mkspecs/linux-g++/qmake.conf:
/opt/qt-5.15.10/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/qt-5.15.10/mkspecs/features/exclusive_builds.prf:
/opt/qt-5.15.10/mkspecs/features/toolchain.prf:
/opt/qt-5.15.10/mkspecs/features/default_pre.prf:
/opt/qt-5.15.10/mkspecs/features/resolve_config.prf:
/opt/qt-5.15.10/mkspecs/features/default_post.prf:
/opt/qt-5.15.10/mkspecs/features/warn_on.prf:
/opt/qt-5.15.10/mkspecs/features/qt.prf:
/opt/qt-5.15.10/mkspecs/features/resources_functions.prf:
/opt/qt-5.15.10/mkspecs/features/resources.prf:
/opt/qt-5.15.10/mkspecs/features/moc.prf:
/opt/qt-5.15.10/mkspecs/features/unix/opengl.prf:
/opt/qt-5.15.10/mkspecs/features/uic.prf:
/opt/qt-5.15.10/mkspecs/features/unix/thread.prf:
/opt/qt-5.15.10/mkspecs/features/qmake_use.prf:
/opt/qt-5.15.10/mkspecs/features/file_copies.prf:
/opt/qt-5.15.10/mkspecs/features/testcase_targets.prf:
/opt/qt-5.15.10/mkspecs/features/exceptions.prf:
/opt/qt-5.15.10/mkspecs/features/yacc.prf:
/opt/qt-5.15.10/mkspecs/features/lex.prf:
JsonEditor.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile JsonEditor.pro

qmake_all: FORCE


all: Makefile JsonEditor

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/qt-5.15.10/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents JsonEditorDialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp JsonEditorDialog.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

run: $(TARGET)
	./run_with_server.sh

double_test: $(TARGET)
	./double_test.sh

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/qt-5.15.10/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /opt/qt-5.15.10/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_JsonEditorDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_JsonEditorDialog.cpp
moc_JsonEditorDialog.cpp: JsonEditorDialog.h \
		/opt/qt-5.15.10/include/QtWidgets/QDialog \
		/opt/qt-5.15.10/include/QtWidgets/qdialog.h \
		/opt/qt-5.15.10/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt-5.15.10/include/QtGui/qtguiglobal.h \
		/opt/qt-5.15.10/include/QtCore/qglobal.h \
		/opt/qt-5.15.10/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt-5.15.10/include/QtCore/qconfig.h \
		/opt/qt-5.15.10/include/QtCore/qtcore-config.h \
		/opt/qt-5.15.10/include/QtCore/qsystemdetection.h \
		/opt/qt-5.15.10/include/QtCore/qprocessordetection.h \
		/opt/qt-5.15.10/include/QtCore/qcompilerdetection.h \
		/opt/qt-5.15.10/include/QtCore/qtypeinfo.h \
		/opt/qt-5.15.10/include/QtCore/qsysinfo.h \
		/opt/qt-5.15.10/include/QtCore/qlogging.h \
		/opt/qt-5.15.10/include/QtCore/qflags.h \
		/opt/qt-5.15.10/include/QtCore/qatomic.h \
		/opt/qt-5.15.10/include/QtCore/qbasicatomic.h \
		/opt/qt-5.15.10/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-5.15.10/include/QtCore/qgenericatomic.h \
		/opt/qt-5.15.10/include/QtCore/qatomic_cxx11.h \
		/opt/qt-5.15.10/include/QtCore/qatomic_msvc.h \
		/opt/qt-5.15.10/include/QtCore/qglobalstatic.h \
		/opt/qt-5.15.10/include/QtCore/qmutex.h \
		/opt/qt-5.15.10/include/QtCore/qtsan_impl.h \
		/opt/qt-5.15.10/include/QtCore/qnumeric.h \
		/opt/qt-5.15.10/include/QtCore/qversiontagging.h \
		/opt/qt-5.15.10/include/QtGui/qtgui-config.h \
		/opt/qt-5.15.10/include/QtWidgets/qtwidgets-config.h \
		/opt/qt-5.15.10/include/QtWidgets/qwidget.h \
		/opt/qt-5.15.10/include/QtGui/qwindowdefs.h \
		/opt/qt-5.15.10/include/QtCore/qobjectdefs.h \
		/opt/qt-5.15.10/include/QtCore/qnamespace.h \
		/opt/qt-5.15.10/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-5.15.10/include/QtGui/qwindowdefs_win.h \
		/opt/qt-5.15.10/include/QtCore/qobject.h \
		/opt/qt-5.15.10/include/QtCore/qstring.h \
		/opt/qt-5.15.10/include/QtCore/qchar.h \
		/opt/qt-5.15.10/include/QtCore/qbytearray.h \
		/opt/qt-5.15.10/include/QtCore/qrefcount.h \
		/opt/qt-5.15.10/include/QtCore/qarraydata.h \
		/opt/qt-5.15.10/include/QtCore/qstringliteral.h \
		/opt/qt-5.15.10/include/QtCore/qstringalgorithms.h \
		/opt/qt-5.15.10/include/QtCore/qstringview.h \
		/opt/qt-5.15.10/include/QtCore/qstringbuilder.h \
		/opt/qt-5.15.10/include/QtCore/qlist.h \
		/opt/qt-5.15.10/include/QtCore/qalgorithms.h \
		/opt/qt-5.15.10/include/QtCore/qiterator.h \
		/opt/qt-5.15.10/include/QtCore/qhashfunctions.h \
		/opt/qt-5.15.10/include/QtCore/qpair.h \
		/opt/qt-5.15.10/include/QtCore/qvector.h \
		/opt/qt-5.15.10/include/QtCore/qcontainertools_impl.h \
		/opt/qt-5.15.10/include/QtCore/qpoint.h \
		/opt/qt-5.15.10/include/QtCore/qbytearraylist.h \
		/opt/qt-5.15.10/include/QtCore/qstringlist.h \
		/opt/qt-5.15.10/include/QtCore/qregexp.h \
		/opt/qt-5.15.10/include/QtCore/qstringmatcher.h \
		/opt/qt-5.15.10/include/QtCore/qcoreevent.h \
		/opt/qt-5.15.10/include/QtCore/qscopedpointer.h \
		/opt/qt-5.15.10/include/QtCore/qmetatype.h \
		/opt/qt-5.15.10/include/QtCore/qvarlengtharray.h \
		/opt/qt-5.15.10/include/QtCore/qcontainerfwd.h \
		/opt/qt-5.15.10/include/QtCore/qobject_impl.h \
		/opt/qt-5.15.10/include/QtCore/qmargins.h \
		/opt/qt-5.15.10/include/QtGui/qpaintdevice.h \
		/opt/qt-5.15.10/include/QtCore/qrect.h \
		/opt/qt-5.15.10/include/QtCore/qsize.h \
		/opt/qt-5.15.10/include/QtGui/qpalette.h \
		/opt/qt-5.15.10/include/QtGui/qcolor.h \
		/opt/qt-5.15.10/include/QtGui/qrgb.h \
		/opt/qt-5.15.10/include/QtGui/qrgba64.h \
		/opt/qt-5.15.10/include/QtGui/qbrush.h \
		/opt/qt-5.15.10/include/QtGui/qmatrix.h \
		/opt/qt-5.15.10/include/QtGui/qpolygon.h \
		/opt/qt-5.15.10/include/QtGui/qregion.h \
		/opt/qt-5.15.10/include/QtCore/qdatastream.h \
		/opt/qt-5.15.10/include/QtCore/qiodevice.h \
		/opt/qt-5.15.10/include/QtCore/qline.h \
		/opt/qt-5.15.10/include/QtGui/qtransform.h \
		/opt/qt-5.15.10/include/QtGui/qimage.h \
		/opt/qt-5.15.10/include/QtGui/qpixelformat.h \
		/opt/qt-5.15.10/include/QtGui/qpixmap.h \
		/opt/qt-5.15.10/include/QtCore/qsharedpointer.h \
		/opt/qt-5.15.10/include/QtCore/qshareddata.h \
		/opt/qt-5.15.10/include/QtCore/qhash.h \
		/opt/qt-5.15.10/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-5.15.10/include/QtGui/qfont.h \
		/opt/qt-5.15.10/include/QtGui/qfontmetrics.h \
		/opt/qt-5.15.10/include/QtGui/qfontinfo.h \
		/opt/qt-5.15.10/include/QtWidgets/qsizepolicy.h \
		/opt/qt-5.15.10/include/QtGui/qcursor.h \
		/opt/qt-5.15.10/include/QtGui/qkeysequence.h \
		/opt/qt-5.15.10/include/QtGui/qevent.h \
		/opt/qt-5.15.10/include/QtCore/qvariant.h \
		/opt/qt-5.15.10/include/QtCore/qmap.h \
		/opt/qt-5.15.10/include/QtCore/qdebug.h \
		/opt/qt-5.15.10/include/QtCore/qtextstream.h \
		/opt/qt-5.15.10/include/QtCore/qlocale.h \
		/opt/qt-5.15.10/include/QtCore/qset.h \
		/opt/qt-5.15.10/include/QtCore/qcontiguouscache.h \
		/opt/qt-5.15.10/include/QtCore/qurl.h \
		/opt/qt-5.15.10/include/QtCore/qurlquery.h \
		/opt/qt-5.15.10/include/QtCore/qfile.h \
		/opt/qt-5.15.10/include/QtCore/qfiledevice.h \
		/opt/qt-5.15.10/include/QtGui/qvector2d.h \
		/opt/qt-5.15.10/include/QtGui/qtouchdevice.h \
		/opt/qt-5.15.10/include/QtWidgets/QLineEdit \
		/opt/qt-5.15.10/include/QtWidgets/qlineedit.h \
		/opt/qt-5.15.10/include/QtWidgets/qframe.h \
		/opt/qt-5.15.10/include/QtGui/qtextcursor.h \
		/opt/qt-5.15.10/include/QtGui/qtextformat.h \
		/opt/qt-5.15.10/include/QtGui/qpen.h \
		/opt/qt-5.15.10/include/QtGui/qtextoption.h \
		/opt/qt-5.15.10/include/QtWidgets/QTextEdit \
		/opt/qt-5.15.10/include/QtWidgets/qtextedit.h \
		/opt/qt-5.15.10/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt-5.15.10/include/QtGui/qtextdocument.h \
		/opt/qt-5.15.10/include/QtWidgets/QPushButton \
		/opt/qt-5.15.10/include/QtWidgets/qpushbutton.h \
		/opt/qt-5.15.10/include/QtWidgets/qabstractbutton.h \
		/opt/qt-5.15.10/include/QtGui/qicon.h \
		/opt/qt-5.15.10/include/QtWidgets/QVBoxLayout \
		/opt/qt-5.15.10/include/QtWidgets/qboxlayout.h \
		/opt/qt-5.15.10/include/QtWidgets/qlayout.h \
		/opt/qt-5.15.10/include/QtWidgets/qlayoutitem.h \
		/opt/qt-5.15.10/include/QtWidgets/qgridlayout.h \
		/opt/qt-5.15.10/include/QtWidgets/QHBoxLayout \
		/opt/qt-5.15.10/include/QtWidgets/QLabel \
		/opt/qt-5.15.10/include/QtWidgets/qlabel.h \
		/opt/qt-5.15.10/include/QtCore/QJsonDocument \
		/opt/qt-5.15.10/include/QtCore/qjsondocument.h \
		/opt/qt-5.15.10/include/QtCore/qjsonvalue.h \
		/opt/qt-5.15.10/include/QtCore/qcborvalue.h \
		/opt/qt-5.15.10/include/QtCore/qdatetime.h \
		/opt/qt-5.15.10/include/QtCore/qcborcommon.h \
		/opt/qt-5.15.10/include/QtCore/qregularexpression.h \
		/opt/qt-5.15.10/include/QtCore/quuid.h \
		/opt/qt-5.15.10/include/QtCore/QJsonObject \
		/opt/qt-5.15.10/include/QtCore/qjsonobject.h \
		/opt/qt-5.15.10/include/QtNetwork/QNetworkAccessManager \
		/opt/qt-5.15.10/include/QtNetwork/qnetworkaccessmanager.h \
		/opt/qt-5.15.10/include/QtNetwork/qtnetworkglobal.h \
		/opt/qt-5.15.10/include/QtNetwork/qtnetwork-config.h \
		/opt/qt-5.15.10/include/QtNetwork/qnetworkrequest.h \
		/opt/qt-5.15.10/include/QtCore/QSharedDataPointer \
		/opt/qt-5.15.10/include/QtCore/QString \
		/opt/qt-5.15.10/include/QtCore/QUrl \
		/opt/qt-5.15.10/include/QtCore/QVariant \
		/opt/qt-5.15.10/include/QtCore/QVector \
		/opt/qt-5.15.10/include/QtCore/QObject \
		/opt/qt-5.15.10/include/QtNetwork/QSslConfiguration \
		/opt/qt-5.15.10/include/QtNetwork/qsslconfiguration.h \
		/opt/qt-5.15.10/include/QtNetwork/qsslsocket.h \
		/opt/qt-5.15.10/include/QtNetwork/qtcpsocket.h \
		/opt/qt-5.15.10/include/QtNetwork/qabstractsocket.h \
		/opt/qt-5.15.10/include/QtNetwork/qsslerror.h \
		/opt/qt-5.15.10/include/QtNetwork/qsslcertificate.h \
		/opt/qt-5.15.10/include/QtCore/qcryptographichash.h \
		/opt/qt-5.15.10/include/QtNetwork/qssl.h \
		/opt/qt-5.15.10/include/QtCore/QFlags \
		/opt/qt-5.15.10/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		/opt/qt-5.15.10/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		/opt/qt-5.15.10/include/QtCore/QMetaType \
		/opt/qt-5.15.10/include/QtNetwork/QNetworkReply \
		/opt/qt-5.15.10/include/QtNetwork/qnetworkreply.h \
		/opt/qt-5.15.10/include/QtCore/QIODevice \
		/opt/qt-5.15.10/include/QtNetwork/QNetworkRequest \
		/opt/qt-5.15.10/include/QtWidgets/QMessageBox \
		/opt/qt-5.15.10/include/QtWidgets/qmessagebox.h \
		/opt/qt-5.15.10/include/QtCore/QTimer \
		/opt/qt-5.15.10/include/QtCore/qtimer.h \
		/opt/qt-5.15.10/include/QtCore/qbasictimer.h \
		moc_predefs.h \
		/opt/qt-5.15.10/bin/moc
	/opt/qt-5.15.10/bin/moc $(DEFINES) --include /home/tigran/ProjectWithAi/JsonEditor/moc_predefs.h -I/opt/qt-5.15.10/mkspecs/linux-g++ -I/home/tigran/ProjectWithAi/JsonEditor -I/opt/qt-5.15.10/include -I/opt/qt-5.15.10/include/QtWidgets -I/opt/qt-5.15.10/include/QtGui -I/opt/qt-5.15.10/include/QtNetwork -I/opt/qt-5.15.10/include/QtCore -I/opt/kf5/include -I/usr/include/c++/13.2.0 -I/usr/include/c++/13.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.0/include-fixed -I/usr/include JsonEditorDialog.h -o moc_JsonEditorDialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /opt/qt-5.15.10/include/QtWidgets/QApplication \
		/opt/qt-5.15.10/include/QtWidgets/qapplication.h \
		/opt/qt-5.15.10/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt-5.15.10/include/QtGui/qtguiglobal.h \
		/opt/qt-5.15.10/include/QtCore/qglobal.h \
		/opt/qt-5.15.10/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt-5.15.10/include/QtCore/qconfig.h \
		/opt/qt-5.15.10/include/QtCore/qtcore-config.h \
		/opt/qt-5.15.10/include/QtCore/qsystemdetection.h \
		/opt/qt-5.15.10/include/QtCore/qprocessordetection.h \
		/opt/qt-5.15.10/include/QtCore/qcompilerdetection.h \
		/opt/qt-5.15.10/include/QtCore/qtypeinfo.h \
		/opt/qt-5.15.10/include/QtCore/qsysinfo.h \
		/opt/qt-5.15.10/include/QtCore/qlogging.h \
		/opt/qt-5.15.10/include/QtCore/qflags.h \
		/opt/qt-5.15.10/include/QtCore/qatomic.h \
		/opt/qt-5.15.10/include/QtCore/qbasicatomic.h \
		/opt/qt-5.15.10/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-5.15.10/include/QtCore/qgenericatomic.h \
		/opt/qt-5.15.10/include/QtCore/qatomic_cxx11.h \
		/opt/qt-5.15.10/include/QtCore/qatomic_msvc.h \
		/opt/qt-5.15.10/include/QtCore/qglobalstatic.h \
		/opt/qt-5.15.10/include/QtCore/qmutex.h \
		/opt/qt-5.15.10/include/QtCore/qtsan_impl.h \
		/opt/qt-5.15.10/include/QtCore/qnumeric.h \
		/opt/qt-5.15.10/include/QtCore/qversiontagging.h \
		/opt/qt-5.15.10/include/QtGui/qtgui-config.h \
		/opt/qt-5.15.10/include/QtWidgets/qtwidgets-config.h \
		/opt/qt-5.15.10/include/QtCore/qcoreapplication.h \
		/opt/qt-5.15.10/include/QtCore/qstring.h \
		/opt/qt-5.15.10/include/QtCore/qchar.h \
		/opt/qt-5.15.10/include/QtCore/qbytearray.h \
		/opt/qt-5.15.10/include/QtCore/qrefcount.h \
		/opt/qt-5.15.10/include/QtCore/qnamespace.h \
		/opt/qt-5.15.10/include/QtCore/qarraydata.h \
		/opt/qt-5.15.10/include/QtCore/qstringliteral.h \
		/opt/qt-5.15.10/include/QtCore/qstringalgorithms.h \
		/opt/qt-5.15.10/include/QtCore/qstringview.h \
		/opt/qt-5.15.10/include/QtCore/qstringbuilder.h \
		/opt/qt-5.15.10/include/QtCore/qobject.h \
		/opt/qt-5.15.10/include/QtCore/qobjectdefs.h \
		/opt/qt-5.15.10/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-5.15.10/include/QtCore/qlist.h \
		/opt/qt-5.15.10/include/QtCore/qalgorithms.h \
		/opt/qt-5.15.10/include/QtCore/qiterator.h \
		/opt/qt-5.15.10/include/QtCore/qhashfunctions.h \
		/opt/qt-5.15.10/include/QtCore/qpair.h \
		/opt/qt-5.15.10/include/QtCore/qvector.h \
		/opt/qt-5.15.10/include/QtCore/qcontainertools_impl.h \
		/opt/qt-5.15.10/include/QtCore/qpoint.h \
		/opt/qt-5.15.10/include/QtCore/qbytearraylist.h \
		/opt/qt-5.15.10/include/QtCore/qstringlist.h \
		/opt/qt-5.15.10/include/QtCore/qregexp.h \
		/opt/qt-5.15.10/include/QtCore/qstringmatcher.h \
		/opt/qt-5.15.10/include/QtCore/qcoreevent.h \
		/opt/qt-5.15.10/include/QtCore/qscopedpointer.h \
		/opt/qt-5.15.10/include/QtCore/qmetatype.h \
		/opt/qt-5.15.10/include/QtCore/qvarlengtharray.h \
		/opt/qt-5.15.10/include/QtCore/qcontainerfwd.h \
		/opt/qt-5.15.10/include/QtCore/qobject_impl.h \
		/opt/qt-5.15.10/include/QtCore/qeventloop.h \
		/opt/qt-5.15.10/include/QtGui/qwindowdefs.h \
		/opt/qt-5.15.10/include/QtGui/qwindowdefs_win.h \
		/opt/qt-5.15.10/include/QtCore/qsize.h \
		/opt/qt-5.15.10/include/QtCore/qmargins.h \
		/opt/qt-5.15.10/include/QtGui/qcursor.h \
		/opt/qt-5.15.10/include/QtWidgets/qdesktopwidget.h \
		/opt/qt-5.15.10/include/QtWidgets/qwidget.h \
		/opt/qt-5.15.10/include/QtGui/qpaintdevice.h \
		/opt/qt-5.15.10/include/QtCore/qrect.h \
		/opt/qt-5.15.10/include/QtGui/qpalette.h \
		/opt/qt-5.15.10/include/QtGui/qcolor.h \
		/opt/qt-5.15.10/include/QtGui/qrgb.h \
		/opt/qt-5.15.10/include/QtGui/qrgba64.h \
		/opt/qt-5.15.10/include/QtGui/qbrush.h \
		/opt/qt-5.15.10/include/QtGui/qmatrix.h \
		/opt/qt-5.15.10/include/QtGui/qpolygon.h \
		/opt/qt-5.15.10/include/QtGui/qregion.h \
		/opt/qt-5.15.10/include/QtCore/qdatastream.h \
		/opt/qt-5.15.10/include/QtCore/qiodevice.h \
		/opt/qt-5.15.10/include/QtCore/qline.h \
		/opt/qt-5.15.10/include/QtGui/qtransform.h \
		/opt/qt-5.15.10/include/QtGui/qimage.h \
		/opt/qt-5.15.10/include/QtGui/qpixelformat.h \
		/opt/qt-5.15.10/include/QtGui/qpixmap.h \
		/opt/qt-5.15.10/include/QtCore/qsharedpointer.h \
		/opt/qt-5.15.10/include/QtCore/qshareddata.h \
		/opt/qt-5.15.10/include/QtCore/qhash.h \
		/opt/qt-5.15.10/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-5.15.10/include/QtGui/qfont.h \
		/opt/qt-5.15.10/include/QtGui/qfontmetrics.h \
		/opt/qt-5.15.10/include/QtGui/qfontinfo.h \
		/opt/qt-5.15.10/include/QtWidgets/qsizepolicy.h \
		/opt/qt-5.15.10/include/QtGui/qkeysequence.h \
		/opt/qt-5.15.10/include/QtGui/qevent.h \
		/opt/qt-5.15.10/include/QtCore/qvariant.h \
		/opt/qt-5.15.10/include/QtCore/qmap.h \
		/opt/qt-5.15.10/include/QtCore/qdebug.h \
		/opt/qt-5.15.10/include/QtCore/qtextstream.h \
		/opt/qt-5.15.10/include/QtCore/qlocale.h \
		/opt/qt-5.15.10/include/QtCore/qset.h \
		/opt/qt-5.15.10/include/QtCore/qcontiguouscache.h \
		/opt/qt-5.15.10/include/QtCore/qurl.h \
		/opt/qt-5.15.10/include/QtCore/qurlquery.h \
		/opt/qt-5.15.10/include/QtCore/qfile.h \
		/opt/qt-5.15.10/include/QtCore/qfiledevice.h \
		/opt/qt-5.15.10/include/QtGui/qvector2d.h \
		/opt/qt-5.15.10/include/QtGui/qtouchdevice.h \
		/opt/qt-5.15.10/include/QtGui/qguiapplication.h \
		/opt/qt-5.15.10/include/QtGui/qinputmethod.h \
		JsonEditorDialog.h \
		/opt/qt-5.15.10/include/QtWidgets/QDialog \
		/opt/qt-5.15.10/include/QtWidgets/qdialog.h \
		/opt/qt-5.15.10/include/QtWidgets/QLineEdit \
		/opt/qt-5.15.10/include/QtWidgets/qlineedit.h \
		/opt/qt-5.15.10/include/QtWidgets/qframe.h \
		/opt/qt-5.15.10/include/QtGui/qtextcursor.h \
		/opt/qt-5.15.10/include/QtGui/qtextformat.h \
		/opt/qt-5.15.10/include/QtGui/qpen.h \
		/opt/qt-5.15.10/include/QtGui/qtextoption.h \
		/opt/qt-5.15.10/include/QtWidgets/QTextEdit \
		/opt/qt-5.15.10/include/QtWidgets/qtextedit.h \
		/opt/qt-5.15.10/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt-5.15.10/include/QtGui/qtextdocument.h \
		/opt/qt-5.15.10/include/QtWidgets/QPushButton \
		/opt/qt-5.15.10/include/QtWidgets/qpushbutton.h \
		/opt/qt-5.15.10/include/QtWidgets/qabstractbutton.h \
		/opt/qt-5.15.10/include/QtGui/qicon.h \
		/opt/qt-5.15.10/include/QtWidgets/QVBoxLayout \
		/opt/qt-5.15.10/include/QtWidgets/qboxlayout.h \
		/opt/qt-5.15.10/include/QtWidgets/qlayout.h \
		/opt/qt-5.15.10/include/QtWidgets/qlayoutitem.h \
		/opt/qt-5.15.10/include/QtWidgets/qgridlayout.h \
		/opt/qt-5.15.10/include/QtWidgets/QHBoxLayout \
		/opt/qt-5.15.10/include/QtWidgets/QLabel \
		/opt/qt-5.15.10/include/QtWidgets/qlabel.h \
		/opt/qt-5.15.10/include/QtCore/QJsonDocument \
		/opt/qt-5.15.10/include/QtCore/qjsondocument.h \
		/opt/qt-5.15.10/include/QtCore/qjsonvalue.h \
		/opt/qt-5.15.10/include/QtCore/qcborvalue.h \
		/opt/qt-5.15.10/include/QtCore/qdatetime.h \
		/opt/qt-5.15.10/include/QtCore/qcborcommon.h \
		/opt/qt-5.15.10/include/QtCore/qregularexpression.h \
		/opt/qt-5.15.10/include/QtCore/quuid.h \
		/opt/qt-5.15.10/include/QtCore/QJsonObject \
		/opt/qt-5.15.10/include/QtCore/qjsonobject.h \
		/opt/qt-5.15.10/include/QtNetwork/QNetworkAccessManager \
		/opt/qt-5.15.10/include/QtNetwork/qnetworkaccessmanager.h \
		/opt/qt-5.15.10/include/QtNetwork/qtnetworkglobal.h \
		/opt/qt-5.15.10/include/QtNetwork/qtnetwork-config.h \
		/opt/qt-5.15.10/include/QtNetwork/qnetworkrequest.h \
		/opt/qt-5.15.10/include/QtCore/QSharedDataPointer \
		/opt/qt-5.15.10/include/QtCore/QString \
		/opt/qt-5.15.10/include/QtCore/QUrl \
		/opt/qt-5.15.10/include/QtCore/QVariant \
		/opt/qt-5.15.10/include/QtCore/QVector \
		/opt/qt-5.15.10/include/QtCore/QObject \
		/opt/qt-5.15.10/include/QtNetwork/QSslConfiguration \
		/opt/qt-5.15.10/include/QtNetwork/qsslconfiguration.h \
		/opt/qt-5.15.10/include/QtNetwork/qsslsocket.h \
		/opt/qt-5.15.10/include/QtNetwork/qtcpsocket.h \
		/opt/qt-5.15.10/include/QtNetwork/qabstractsocket.h \
		/opt/qt-5.15.10/include/QtNetwork/qsslerror.h \
		/opt/qt-5.15.10/include/QtNetwork/qsslcertificate.h \
		/opt/qt-5.15.10/include/QtCore/qcryptographichash.h \
		/opt/qt-5.15.10/include/QtNetwork/qssl.h \
		/opt/qt-5.15.10/include/QtCore/QFlags \
		/opt/qt-5.15.10/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		/opt/qt-5.15.10/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		/opt/qt-5.15.10/include/QtCore/QMetaType \
		/opt/qt-5.15.10/include/QtNetwork/QNetworkReply \
		/opt/qt-5.15.10/include/QtNetwork/qnetworkreply.h \
		/opt/qt-5.15.10/include/QtCore/QIODevice \
		/opt/qt-5.15.10/include/QtNetwork/QNetworkRequest \
		/opt/qt-5.15.10/include/QtWidgets/QMessageBox \
		/opt/qt-5.15.10/include/QtWidgets/qmessagebox.h \
		/opt/qt-5.15.10/include/QtCore/QTimer \
		/opt/qt-5.15.10/include/QtCore/qtimer.h \
		/opt/qt-5.15.10/include/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

JsonEditorDialog.o: JsonEditorDialog.cpp JsonEditorDialog.h \
		/opt/qt-5.15.10/include/QtWidgets/QDialog \
		/opt/qt-5.15.10/include/QtWidgets/qdialog.h \
		/opt/qt-5.15.10/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt-5.15.10/include/QtGui/qtguiglobal.h \
		/opt/qt-5.15.10/include/QtCore/qglobal.h \
		/opt/qt-5.15.10/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt-5.15.10/include/QtCore/qconfig.h \
		/opt/qt-5.15.10/include/QtCore/qtcore-config.h \
		/opt/qt-5.15.10/include/QtCore/qsystemdetection.h \
		/opt/qt-5.15.10/include/QtCore/qprocessordetection.h \
		/opt/qt-5.15.10/include/QtCore/qcompilerdetection.h \
		/opt/qt-5.15.10/include/QtCore/qtypeinfo.h \
		/opt/qt-5.15.10/include/QtCore/qsysinfo.h \
		/opt/qt-5.15.10/include/QtCore/qlogging.h \
		/opt/qt-5.15.10/include/QtCore/qflags.h \
		/opt/qt-5.15.10/include/QtCore/qatomic.h \
		/opt/qt-5.15.10/include/QtCore/qbasicatomic.h \
		/opt/qt-5.15.10/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-5.15.10/include/QtCore/qgenericatomic.h \
		/opt/qt-5.15.10/include/QtCore/qatomic_cxx11.h \
		/opt/qt-5.15.10/include/QtCore/qatomic_msvc.h \
		/opt/qt-5.15.10/include/QtCore/qglobalstatic.h \
		/opt/qt-5.15.10/include/QtCore/qmutex.h \
		/opt/qt-5.15.10/include/QtCore/qtsan_impl.h \
		/opt/qt-5.15.10/include/QtCore/qnumeric.h \
		/opt/qt-5.15.10/include/QtCore/qversiontagging.h \
		/opt/qt-5.15.10/include/QtGui/qtgui-config.h \
		/opt/qt-5.15.10/include/QtWidgets/qtwidgets-config.h \
		/opt/qt-5.15.10/include/QtWidgets/qwidget.h \
		/opt/qt-5.15.10/include/QtGui/qwindowdefs.h \
		/opt/qt-5.15.10/include/QtCore/qobjectdefs.h \
		/opt/qt-5.15.10/include/QtCore/qnamespace.h \
		/opt/qt-5.15.10/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-5.15.10/include/QtGui/qwindowdefs_win.h \
		/opt/qt-5.15.10/include/QtCore/qobject.h \
		/opt/qt-5.15.10/include/QtCore/qstring.h \
		/opt/qt-5.15.10/include/QtCore/qchar.h \
		/opt/qt-5.15.10/include/QtCore/qbytearray.h \
		/opt/qt-5.15.10/include/QtCore/qrefcount.h \
		/opt/qt-5.15.10/include/QtCore/qarraydata.h \
		/opt/qt-5.15.10/include/QtCore/qstringliteral.h \
		/opt/qt-5.15.10/include/QtCore/qstringalgorithms.h \
		/opt/qt-5.15.10/include/QtCore/qstringview.h \
		/opt/qt-5.15.10/include/QtCore/qstringbuilder.h \
		/opt/qt-5.15.10/include/QtCore/qlist.h \
		/opt/qt-5.15.10/include/QtCore/qalgorithms.h \
		/opt/qt-5.15.10/include/QtCore/qiterator.h \
		/opt/qt-5.15.10/include/QtCore/qhashfunctions.h \
		/opt/qt-5.15.10/include/QtCore/qpair.h \
		/opt/qt-5.15.10/include/QtCore/qvector.h \
		/opt/qt-5.15.10/include/QtCore/qcontainertools_impl.h \
		/opt/qt-5.15.10/include/QtCore/qpoint.h \
		/opt/qt-5.15.10/include/QtCore/qbytearraylist.h \
		/opt/qt-5.15.10/include/QtCore/qstringlist.h \
		/opt/qt-5.15.10/include/QtCore/qregexp.h \
		/opt/qt-5.15.10/include/QtCore/qstringmatcher.h \
		/opt/qt-5.15.10/include/QtCore/qcoreevent.h \
		/opt/qt-5.15.10/include/QtCore/qscopedpointer.h \
		/opt/qt-5.15.10/include/QtCore/qmetatype.h \
		/opt/qt-5.15.10/include/QtCore/qvarlengtharray.h \
		/opt/qt-5.15.10/include/QtCore/qcontainerfwd.h \
		/opt/qt-5.15.10/include/QtCore/qobject_impl.h \
		/opt/qt-5.15.10/include/QtCore/qmargins.h \
		/opt/qt-5.15.10/include/QtGui/qpaintdevice.h \
		/opt/qt-5.15.10/include/QtCore/qrect.h \
		/opt/qt-5.15.10/include/QtCore/qsize.h \
		/opt/qt-5.15.10/include/QtGui/qpalette.h \
		/opt/qt-5.15.10/include/QtGui/qcolor.h \
		/opt/qt-5.15.10/include/QtGui/qrgb.h \
		/opt/qt-5.15.10/include/QtGui/qrgba64.h \
		/opt/qt-5.15.10/include/QtGui/qbrush.h \
		/opt/qt-5.15.10/include/QtGui/qmatrix.h \
		/opt/qt-5.15.10/include/QtGui/qpolygon.h \
		/opt/qt-5.15.10/include/QtGui/qregion.h \
		/opt/qt-5.15.10/include/QtCore/qdatastream.h \
		/opt/qt-5.15.10/include/QtCore/qiodevice.h \
		/opt/qt-5.15.10/include/QtCore/qline.h \
		/opt/qt-5.15.10/include/QtGui/qtransform.h \
		/opt/qt-5.15.10/include/QtGui/qimage.h \
		/opt/qt-5.15.10/include/QtGui/qpixelformat.h \
		/opt/qt-5.15.10/include/QtGui/qpixmap.h \
		/opt/qt-5.15.10/include/QtCore/qsharedpointer.h \
		/opt/qt-5.15.10/include/QtCore/qshareddata.h \
		/opt/qt-5.15.10/include/QtCore/qhash.h \
		/opt/qt-5.15.10/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-5.15.10/include/QtGui/qfont.h \
		/opt/qt-5.15.10/include/QtGui/qfontmetrics.h \
		/opt/qt-5.15.10/include/QtGui/qfontinfo.h \
		/opt/qt-5.15.10/include/QtWidgets/qsizepolicy.h \
		/opt/qt-5.15.10/include/QtGui/qcursor.h \
		/opt/qt-5.15.10/include/QtGui/qkeysequence.h \
		/opt/qt-5.15.10/include/QtGui/qevent.h \
		/opt/qt-5.15.10/include/QtCore/qvariant.h \
		/opt/qt-5.15.10/include/QtCore/qmap.h \
		/opt/qt-5.15.10/include/QtCore/qdebug.h \
		/opt/qt-5.15.10/include/QtCore/qtextstream.h \
		/opt/qt-5.15.10/include/QtCore/qlocale.h \
		/opt/qt-5.15.10/include/QtCore/qset.h \
		/opt/qt-5.15.10/include/QtCore/qcontiguouscache.h \
		/opt/qt-5.15.10/include/QtCore/qurl.h \
		/opt/qt-5.15.10/include/QtCore/qurlquery.h \
		/opt/qt-5.15.10/include/QtCore/qfile.h \
		/opt/qt-5.15.10/include/QtCore/qfiledevice.h \
		/opt/qt-5.15.10/include/QtGui/qvector2d.h \
		/opt/qt-5.15.10/include/QtGui/qtouchdevice.h \
		/opt/qt-5.15.10/include/QtWidgets/QLineEdit \
		/opt/qt-5.15.10/include/QtWidgets/qlineedit.h \
		/opt/qt-5.15.10/include/QtWidgets/qframe.h \
		/opt/qt-5.15.10/include/QtGui/qtextcursor.h \
		/opt/qt-5.15.10/include/QtGui/qtextformat.h \
		/opt/qt-5.15.10/include/QtGui/qpen.h \
		/opt/qt-5.15.10/include/QtGui/qtextoption.h \
		/opt/qt-5.15.10/include/QtWidgets/QTextEdit \
		/opt/qt-5.15.10/include/QtWidgets/qtextedit.h \
		/opt/qt-5.15.10/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt-5.15.10/include/QtGui/qtextdocument.h \
		/opt/qt-5.15.10/include/QtWidgets/QPushButton \
		/opt/qt-5.15.10/include/QtWidgets/qpushbutton.h \
		/opt/qt-5.15.10/include/QtWidgets/qabstractbutton.h \
		/opt/qt-5.15.10/include/QtGui/qicon.h \
		/opt/qt-5.15.10/include/QtWidgets/QVBoxLayout \
		/opt/qt-5.15.10/include/QtWidgets/qboxlayout.h \
		/opt/qt-5.15.10/include/QtWidgets/qlayout.h \
		/opt/qt-5.15.10/include/QtWidgets/qlayoutitem.h \
		/opt/qt-5.15.10/include/QtWidgets/qgridlayout.h \
		/opt/qt-5.15.10/include/QtWidgets/QHBoxLayout \
		/opt/qt-5.15.10/include/QtWidgets/QLabel \
		/opt/qt-5.15.10/include/QtWidgets/qlabel.h \
		/opt/qt-5.15.10/include/QtCore/QJsonDocument \
		/opt/qt-5.15.10/include/QtCore/qjsondocument.h \
		/opt/qt-5.15.10/include/QtCore/qjsonvalue.h \
		/opt/qt-5.15.10/include/QtCore/qcborvalue.h \
		/opt/qt-5.15.10/include/QtCore/qdatetime.h \
		/opt/qt-5.15.10/include/QtCore/qcborcommon.h \
		/opt/qt-5.15.10/include/QtCore/qregularexpression.h \
		/opt/qt-5.15.10/include/QtCore/quuid.h \
		/opt/qt-5.15.10/include/QtCore/QJsonObject \
		/opt/qt-5.15.10/include/QtCore/qjsonobject.h \
		/opt/qt-5.15.10/include/QtNetwork/QNetworkAccessManager \
		/opt/qt-5.15.10/include/QtNetwork/qnetworkaccessmanager.h \
		/opt/qt-5.15.10/include/QtNetwork/qtnetworkglobal.h \
		/opt/qt-5.15.10/include/QtNetwork/qtnetwork-config.h \
		/opt/qt-5.15.10/include/QtNetwork/qnetworkrequest.h \
		/opt/qt-5.15.10/include/QtCore/QSharedDataPointer \
		/opt/qt-5.15.10/include/QtCore/QString \
		/opt/qt-5.15.10/include/QtCore/QUrl \
		/opt/qt-5.15.10/include/QtCore/QVariant \
		/opt/qt-5.15.10/include/QtCore/QVector \
		/opt/qt-5.15.10/include/QtCore/QObject \
		/opt/qt-5.15.10/include/QtNetwork/QSslConfiguration \
		/opt/qt-5.15.10/include/QtNetwork/qsslconfiguration.h \
		/opt/qt-5.15.10/include/QtNetwork/qsslsocket.h \
		/opt/qt-5.15.10/include/QtNetwork/qtcpsocket.h \
		/opt/qt-5.15.10/include/QtNetwork/qabstractsocket.h \
		/opt/qt-5.15.10/include/QtNetwork/qsslerror.h \
		/opt/qt-5.15.10/include/QtNetwork/qsslcertificate.h \
		/opt/qt-5.15.10/include/QtCore/qcryptographichash.h \
		/opt/qt-5.15.10/include/QtNetwork/qssl.h \
		/opt/qt-5.15.10/include/QtCore/QFlags \
		/opt/qt-5.15.10/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		/opt/qt-5.15.10/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		/opt/qt-5.15.10/include/QtCore/QMetaType \
		/opt/qt-5.15.10/include/QtNetwork/QNetworkReply \
		/opt/qt-5.15.10/include/QtNetwork/qnetworkreply.h \
		/opt/qt-5.15.10/include/QtCore/QIODevice \
		/opt/qt-5.15.10/include/QtNetwork/QNetworkRequest \
		/opt/qt-5.15.10/include/QtWidgets/QMessageBox \
		/opt/qt-5.15.10/include/QtWidgets/qmessagebox.h \
		/opt/qt-5.15.10/include/QtCore/QTimer \
		/opt/qt-5.15.10/include/QtCore/qtimer.h \
		/opt/qt-5.15.10/include/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JsonEditorDialog.o JsonEditorDialog.cpp

moc_JsonEditorDialog.o: moc_JsonEditorDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_JsonEditorDialog.o moc_JsonEditorDialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/JsonEditor/bin || mkdir -p $(INSTALL_ROOT)/opt/JsonEditor/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/JsonEditor/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/JsonEditor/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/JsonEditor/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/JsonEditor/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

