#setting environment variable for self-signed certificate ignorance
#NOTE THIS LINE NEEDS TO BE DELETED IN RELEASE MODE
#export NODE_TLS_REJECT_UNAUTHORIZED=0

# Defining ports
METAX_PORT=
READ_PORT=
WRITE_PORT=

# Metax self signed certs
SELF_PRIVKEY=../certs/metax.key
SELF_CERT=../certs/metax.crt

# trusting own self signed cert
NODE_EXTRA_CA_CERTS=$SELF_CERT

# Let's Encrypt key and cert
LE_PRIVKEY=/home/demo/certs/privkey.pem
LE_CERT=/home/dema/certs/fullchain.pem

# Setting strong TLS ciphers
NODE_OPTIONS=--tls-cipher-list='TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256'

current_datetime=$(date +"%Y-%m-%d_%H-%M-%S")
SITEMAP_UUID=__SITEMAPUUID__
